### ISSUE TITLE
How to open it to the public?

### ISSUE THREAD

**Issue by Zloka** [kaimallea/csgo#31]
Seems to work just fine locally, but how do I host it online? I tried assigning it my IP, but then the logs just output the following, while restarting every 10 seconds:
`WARNING: NET_OpenSocket: bind: Cannot assign requested address
Couldn't allocate any server IP port, tried 1 addresses <IP REDACTED>Tue Apr  7 19:39:11 UTC 2020: Server restart in 10 seconds`

**Comment by 0BuRner** [comment]
I guess you have to use IP address of the host you are running the server on. Then, in your router admin panel, you have to forward external port to internal IP/PORT to pass through NAT (https://www.howtogeek.com/66214/how-to-forward-ports-on-your-router/)

**Comment by christiansenandi** [comment]
As 0BuRner stated you need to point your server to your local ip(hosts ip).

Running this as Kaimallea already have in his readme:

docker run \
  --rm \
  --interactive \
  --tty \
  --detach \
  --mount source=csgo-data,target=/home/steam/csgo \
  --network=host \
  **--publish 27015:27015/tcp \  #Insert any port number here** 
  --env "SERVER_HOSTNAME=hostname" \
  --env "SERVER_PASSWORD=password" \
  --env "RCON_PASSWORD=rconpassword" \
  --env "STEAM_ACCOUNT=gamelogintoken" \
  --env "AUTHKEY=webapikey" \
  --env "SOURCEMOD_ADMINS=STEAM_1:0:123456,STEAM_1:0:654321" \
  kmallea/csgo

When you have added the --publish and a port you can then portforward in your router at home so that connections to that port will be forwarded to your serveres ip and port.

**Comment by kaimallea** [comment]
@Zloka hi, are you still having issues? The error you shared usually means something is already running on the IP and port combo. Make sure there isn't another instance already running.

**Comment by Zloka** [comment]
Hey, thanks for your suggestions.

I tried most of what you suggested: 

1. Using  `--network=host \`
2. Explicitly specifying IP and publishing ports.

Still, I couldn't get it to work. I suspect it's not impossible that I may have had another project running. I'm going to try it on another PC, as that is what I'll be using for hosting anyways. I'll re-open if the problem still occurs on it :)
